Repository UPB-FILS-ALF/upb-fils-alf.github.io, pull requests merged in 2024-02, with the labels that each got.

#1 Pull request labeler
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: workflow

#3 Fix the labeler path for the website
  .github/labeler.yml
Labels: workflow

#6 Rust to Kotlin
  docs/tp/01.md
Labels: tp

#5 Add content to the first page
  docusaurus.config.ts
  src/components/HomepageFeatures/index.tsx
  src/pages/index.tsx
  static/img/kotlin_logo.svg
  static/img/language_logo.svg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
  static/img/wasm_logo.svg
Labels: website

#7 Add homework placeholder
  docs/devoir/01.md
  docs/devoir/02.md
  docs/devoir/03.md
  docs/devoir/04.md
  docs/devoir/_category_.json
  docusaurus.config.ts
Labels: website, devoir

#8 Tp1
  docs/tp/01.md
  docs/tp/images/01_new_kotlin_project.png
Labels: tp

#11 Update license
  docusaurus.config.ts
Labels: website

#12 Add introduction
  docs/cours/_category_.json
  docs/devoir/_category_.json
  docs/intro/images/alexandru_radovici.jpg
  docs/intro/images/amalia_simion.jpg
  docs/intro/images/mihai_costin.jpg
  docs/intro/index.md
  docs/tp/_category_.json
  docusaurus.config.ts
  src/pages/index.tsx
Labels: website, tp, devoir, cours

#10 TP3 first iteration
  docs/tp/tp03/images/03_dfa.png
  docs/tp/tp03/images/03_ex1.png
  docs/tp/tp03/images/03_nfa.png
  docs/tp/tp03/index.md
  docusaurus.config.ts
  package-lock.json
  package.json
Labels: website, tp

#19 Fix lab links to tp/n
  docs/tp/01/images/01_new_kotlin_project.png
  docs/tp/01/index.md
  docs/tp/03/images/03_dfa.png
  docs/tp/03/images/03_ex1.png
  docs/tp/03/images/03_nfa.png
  docs/tp/03/index.md
Labels: bug, tp

#14 Tp4
  docs/tp/04/images/04_etcpasswd_contents.png
  docs/tp/04/index.md
Labels: tp

#20 Add cours 1
  docs/cours/01.md
  static/cours/alf_1.pdf
Labels: website, cours

#21 Fix favicon
  docusaurus.config.ts
  static/img/favicon.ico
  static/img/logo.png
  static/img/logo.svg
Labels: website

#22 Add social card
  docusaurus.config.ts
  static/img/alf-social-card.png
  static/img/docusaurus-social-card.jpg
Labels: website

#23 Changed tp numbers
  docs/tp/00/images/00_new_kotlin_project.png
  docs/tp/00/index.md
  docs/tp/01.md
  docs/tp/02/images/02_dfa.png
  docs/tp/02/images/02_ex1.png
  docs/tp/02/images/02_nfa.png
  docs/tp/02/index.md
  docs/tp/03/images/03_etcpasswd_contents.png
  docs/tp/03/index.md
  docs/tp/04/index.md
Labels: tp
